import React from 'react';
import Header from './components/HeaderFix';
import FileCard from './components/FileCard';
import { Sparkles, BarChart3, Database } from 'lucide-react';

const mockFiles = [
  { id: 1, name: 'Neural_Network_Weights.bin', date: 'JAN 2026', tags: ['Core', 'ML'], summary: 'Optimized weights for the semantic search engine generated by Person 1.' },
  { id: 2, name: 'Project_Nova_Architecture.pdf', date: 'DEC 2025', tags: ['Design', 'CAD'], summary: 'Autonomous navigation schematics for disaster management relief drones.' },
  { id: 3, name: 'Club_Bylaws_Revised.docx', date: 'OCT 2025', tags: ['Admin'], summary: 'Updated organizational structure for the 2026 induction cycle.' }
];

function App() {
  return (
    
    <div className="min-h-screen pb-24">
      {/* Add this at the top of your main <div> in App.jsx */}
      <div className="fixed inset-0 -z-10 overflow-hidden bg-[#130802]">
        
        <div className="absolute inset-0 bg-[url('https://grainy-gradients.vercel.app/noise.svg')] opacity-20 brightness-100 contrast-150"></div>
  {/* Primary Orange Glow - Top Left */}
  <div className="absolute -top-[10%] -left-[10%] w-[50%] h-[50%] bg-[#ff4500]/10 rounded-full blur-[120px] opacity-60 animate-pulse" />
  
  {/* Subtle Center Glow - Inspired by Achievement Stats Section */}
  <div className="absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 w-[70%] h-[70%] bg-[#ff4500]/05 rounded-full blur-[160px]" />
  
  {/* Secondary Deep Blue/Purple Glow - Bottom Right */}
  <div className="absolute -bottom-[10%] -right-[10%] w-[50%] h-[50%] bg-blue-900/10 rounded-full blur-[120px]" />
</div>
      <Header />
      
      {/* Hero Section from Reference */}
      <section className="h-[60vh] flex flex-col justify-center items-center text-center px-4 pt-20">
        <h1 className="text-6xl font-black tracking-tighter text-white mb-4">
          SMART FILES <span className="text-[#ff4500] orange-glow">AI ENGINE</span>
        </h1>
        <p className="text-xl font-light text-slate-400 tracking-[0.3em] uppercase">
          Code For Future Intelligence
        </p>
        <div className="mt-12 flex gap-4">
           <button className="px-8 py-3 border-2 border-[#ff4500] rounded-full font-bold text-sm hover:bg-[#ff4500] transition-all">EXPLORE CLUSTERS</button>
           <button className="px-8 py-3 bg-white text-black rounded-full font-bold text-sm">INITIATE SCAN</button>
        </div>
      </section>

      {/* Content Grid */}
      <main className="max-w-7xl mx-auto px-8 grid grid-cols-1 md:grid-cols-3 gap-8">
        <div className="col-span-full mb-4">
           <h2 className="text-2xl font-bold uppercase tracking-widest border-l-4 border-[#ff4500] pl-4">
             Recent <span className="text-[#ff4500]">Intelligence</span>
           </h2>
        </div>
        {mockFiles.map(file => (
          <FileCard key={file.id} file={file} />
        ))}
      </main>

      {/* Stats Footer mimicking the Achievements stats */}
      <div className="fixed bottom-0 left-0 w-full glass-panel h-16 border-t-white/10 flex items-center justify-around px-20">
        <div className="flex items-center gap-3 text-xs font-bold tracking-tighter">
          <Database className="text-[#ff4500]" size={16}/> 1.2K VECTORS
        </div>
        <div className="flex items-center gap-3 text-xs font-bold tracking-tighter">
          <Sparkles className="text-[#ff4500]" size={16}/> 8 RESEARCH NODES
        </div>
        <div className="flex items-center gap-3 text-xs font-bold tracking-tighter">
          <BarChart3 className="text-[#ff4500]" size={16}/> 98% SIMILARITY
        </div>
      </div>
    </div>
  );
}

export default App;